// ════════════════════════════════════════════════════════════
//  Caulis — Perenual service layer + species library
//  Shaped 1:1 on the Perenual v2 API (perenual.com/docs/api).
//  Live mode activates when an API key is saved (Settings);
//  otherwise a bundled, schema-accurate library backs the
//  prototype so it is fully functional offline.
// ════════════════════════════════════════════════════════════

const WIKI = 'https://commons.wikimedia.org/wiki/Special:FilePath/';
const img = (file) => WIKI + file;

// A Perenual-shaped record: common_name, scientific_name[], cycle,
// watering, watering_general_benchmark{value,unit}, sunlight[],
// care_level, indoor, description, default_image{regular_url,...}.
// `_care` / `_fact` are app-side care copy (Perenual's care guide
// endpoint is a paid tier; we hand-author concise notes here).
const PERENUAL = [
  { id:1442, common_name:'Monstera', scientific_name:['Monstera deliciosa'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['part shade','filtered shade'], care_level:'Medium', indoor:true,
    default_image:{ regular_url: img('Monstera_deliciosa3.jpg') },
    _care:'Water when the top 5cm of soil is dry. Wipe leaves monthly.',
    _fact:'Its leaf holes are called fenestrations — they let light reach lower leaves.' },

  { id:832, common_name:'Fiddle Leaf', scientific_name:['Ficus lyrata'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['full sun','part shade'], care_level:'Medium-High', indoor:true,
    default_image:{ regular_url: img('Ficus_lyrata.jpg') },
    _care:'Keep soil evenly moist, never soggy. Hates being moved.',
    _fact:'A single fiddle leaf can grow up to 45cm long indoors.' },

  { id:2056, common_name:'Snake Plant', scientific_name:['Sansevieria trifasciata'], cycle:'Perennial',
    watering:'Minimum', watering_general_benchmark:{value:'14', unit:'days'},
    sunlight:['full shade','part shade','full sun'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Sansevieria_trifasciata_1.jpg') },
    _care:'Let dry fully between drinks. Tolerates neglect well.',
    _fact:'NASA lists it among the best plants for filtering indoor air.' },

  { id:700, common_name:'Golden Pothos', scientific_name:['Epipremnum aureum'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'6', unit:'days'},
    sunlight:['part shade','full shade'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Epipremnum_aureum_31082012.jpg') },
    _care:'Water weekly; trailing vines love a humid spot.',
    _fact:'Nicknamed "Devil\u2019s Ivy" because it\u2019s nearly impossible to kill.' },

  { id:2110, common_name:'Peace Lily', scientific_name:['Spathiphyllum wallisii'], cycle:'Perennial',
    watering:'Frequent', watering_general_benchmark:{value:'4-5', unit:'days'},
    sunlight:['part shade','full shade'], care_level:'Medium', indoor:true,
    default_image:{ regular_url: img('Spathiphyllum_cochlearispathum_RTBG.jpg') },
    _care:'Keep consistently moist. Droops dramatically when thirsty.',
    _fact:'Its drooping leaves are an honest thirst signal — it perks back up fast.' },

  { id:2003, common_name:'String of Pearls', scientific_name:['Senecio rowleyanus'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'5', unit:'days'},
    sunlight:['full sun','part shade'], care_level:'Medium', indoor:true,
    default_image:{ regular_url: img('Senecio_rowleyanus.jpg') },
    _care:'Soak then dry out completely. Beads store water.',
    _fact:'Each "pearl" has a translucent window that lets in extra light.' },

  { id:1056, common_name:'Calathea', scientific_name:['Calathea orbifolia'], cycle:'Perennial',
    watering:'Frequent', watering_general_benchmark:{value:'6', unit:'days'},
    sunlight:['part shade'], care_level:'High', indoor:true,
    default_image:{ regular_url: img('Calathea_orbifolia.jpg') },
    _care:'Loves humidity and filtered water. Sensitive to tap minerals.',
    _fact:'It folds its leaves up at night — a movement called nyctinasty.' },

  { id:831, common_name:'Rubber Plant', scientific_name:['Ficus elastica'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['part shade','full sun'], care_level:'Low-Medium', indoor:true,
    default_image:{ regular_url: img('Ficus_elastica2.jpg') },
    _care:'Water when top soil dries. Dust the broad leaves often.',
    _fact:'Its sap was once used to make natural rubber.' },

  // — extra species the identifier / search can return —
  { id:2071, common_name:'ZZ Plant', scientific_name:['Zamioculcas zamiifolia'], cycle:'Perennial',
    watering:'Minimum', watering_general_benchmark:{value:'14', unit:'days'},
    sunlight:['full shade','part shade'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Zamioculcas_zamiifolia_1.jpg') },
    _care:'Water sparingly once the soil is fully dry. Thrives on neglect.',
    _fact:'Its rhizomes store water, so it shrugs off a missed watering.' },

  { id:1109, common_name:'Spider Plant', scientific_name:['Chlorophytum comosum'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['part shade','full sun'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Chlorophytum_comosum.jpg') },
    _care:'Keep lightly moist. Pups can be potted into new plants.',
    _fact:'It sends out baby "spiderettes" on long arching stems.' },

  { id:2475, common_name:'Bird of Paradise', scientific_name:['Strelitzia reginae'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['full sun','part shade'], care_level:'Medium', indoor:true,
    default_image:{ regular_url: img('Strelitzia_reginae0.jpg') },
    _care:'Water when the top 5cm dries. Loves warmth and bright light.',
    _fact:'Its flower looks like a tropical bird mid-flight.' },

  { id:1789, common_name:'Philodendron', scientific_name:['Philodendron hederaceum'], cycle:'Perennial',
    watering:'Average', watering_general_benchmark:{value:'7', unit:'days'},
    sunlight:['part shade','full shade'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Philodendron_hederaceum_kz01.jpg') },
    _care:'Let the top of the soil dry between waterings.',
    _fact:'Heartleaf philodendron is one of the easiest vines to grow.' },

  { id:120, common_name:'Aloe Vera', scientific_name:['Aloe barbadensis miller'], cycle:'Perennial',
    watering:'Minimum', watering_general_benchmark:{value:'14', unit:'days'},
    sunlight:['full sun','part shade'], care_level:'Low', indoor:true,
    default_image:{ regular_url: img('Aloe_vera_flower_inset.png') },
    _care:'Soak thoroughly, then let dry out completely.',
    _fact:'Its leaf gel has been used to soothe skin for millennia.' },
];

// ── field mapping: Perenual record → Caulis plant care fields ──
const WATER_DAYS = { Frequent: 4, Average: 7, Minimum: 14, None: 21 };
const titleCase = (s) => s.charAt(0).toUpperCase() + s.slice(1);

function speciesCare(sp) {
  const sunlight = sp.sunlight || [];
  return {
    every:     WATER_DAYS[sp.watering] || 7,
    light:     sunlight.slice(0, 2).map(titleCase).join(' · ') || 'Bright, indirect',
    care:      sp._care || sp.description || 'Water when the top of the soil feels dry.',
    fact:      sp._fact || `${sp.common_name} — care data via Perenual.`,
    watering:  sp.watering || 'Average',
    benchmark: sp.watering_general_benchmark ? `${sp.watering_general_benchmark.value} ${sp.watering_general_benchmark.unit}` : null,
    sunlight,
    image:     sp.default_image ? (sp.default_image.regular_url || sp.default_image.medium_url || null) : null,
    species_id: sp.id,
  };
}

function searchLocalPlants(query) {
  const norm = s => s.toLowerCase().replace(/[-_]/g, ' ');
  const q = norm((query || '').trim());
  if (!q || q.length < 2) return [];
  return INDOOR_PLANTS.filter(p =>
    norm(p.name).includes(q) || norm(p.latin).includes(q)
  ).slice(0, 7);
}

// ── service (live when key present, else bundled library) ──
let API_KEY = '';
try { API_KEY = localStorage.getItem('caulis_perenual_key') || ''; } catch (e) {}
function setApiKey(k) { API_KEY = k || ''; try { localStorage.setItem('caulis_perenual_key', API_KEY); } catch (e) {} }
function hasApiKey() { return !!API_KEY; }
const _wait = (ms) => new Promise(r => setTimeout(r, ms));

async function searchSpecies(query) {
  const q = (query || '').trim().toLowerCase();
  if (API_KEY) {
    try {
      const r = await fetch(`https://perenual.com/api/v2/species-list?key=${API_KEY}&q=${encodeURIComponent(q)}`);
      const j = await r.json();
      if (j && j.data) return j.data;
    } catch (e) { /* fall through to library */ }
  }
  await _wait(280);
  if (!q) return PERENUAL;
  return PERENUAL.filter(p =>
    p.common_name.toLowerCase().includes(q) ||
    p.scientific_name.join(' ').toLowerCase().includes(q));
}

async function getSpeciesDetails(id) {
  if (API_KEY) {
    try {
      const r = await fetch(`https://perenual.com/api/v2/species/details/${id}?key=${API_KEY}`);
      const j = await r.json();
      if (j && j.id) return j;
    } catch (e) {}
  }
  await _wait(180);
  return PERENUAL.find(p => p.id === id) || null;
}

// The real product would POST the photo to the Perenual identification
// API (perenual.com/docs/identify/api); here we simulate a match.
async function identifySpecies() {
  await _wait(1700);
  return PERENUAL[Math.floor(Math.random() * PERENUAL.length)];
}

// ── seed garden: 8 plants built from the species library ──
const _SEED_SPEC = [
  { sid:1442, location:'Living room',       days:2 },
  { sid:832,  location:'Living room',       days:5 },
  { sid:2056, location:'Bedroom',           days:9 },
  { sid:700,  location:'Kitchen windowsill', days:6 },
  { sid:2110, location:'Bathroom',          days:1 },
  { sid:2003, location:'Bedroom',           days:4 },
  { sid:1056, location:'Office',            days:3 },
  { sid:831,  location:'Office',            days:7 },
];
const SEED_PLANTS = _SEED_SPEC.map((s, i) => {
  const sp = PERENUAL.find(p => p.id === s.sid);
  const care = speciesCare(sp);
  return {
    id: i + 1,
    name: sp.common_name,
    latin: sp.scientific_name[0],
    location: s.location,
    days: s.days,
    every: care.every,
    light: care.light,
    care: care.care,
    fact: care.fact,
    watering: care.watering,
    benchmark: care.benchmark,
    sunlight: care.sunlight,
    species_id: sp.id,
    image: care.image,   // preset photo from the API/library
    userImage: null,     // user's own photo, overrides preset when set
  };
});

const INDOOR_PLANTS = [
  {id:7030,name:"African violet",latin:"Saintpaulia ionantha"},
  {id:721,name:"aloe",latin:"Aloe harlana"},
  {id:727,name:"aloe",latin:"Aloe suzannae"},
  {id:728,name:"aloe",latin:"Aloe vera"},
  {id:6068,name:"aluminum plant",latin:"Pilea cadierei"},
  {id:3828,name:"amaryllis",latin:"Hippeastrum (group)"},
  {id:8613,name:"amaryllis",latin:"Hippeastrum cvs."},
  {id:2829,name:"Amazon lily",latin:"Eucharis amazonica"},
  {id:711,name:"Amazonian elephant\'s ear",latin:"Alocasia amazonica \'Polly\'"},
  {id:7639,name:"American evergreen",latin:"Syngonium podophyllum"},
  {id:1457,name:"angel wings",latin:"Caladium bicolor"},
  {id:1220,name:"angelwing begonia",latin:"Begonia \'Sinbad\'"},
  {id:1222,name:"angelwing begonia",latin:"Begonia \'Sophia\'"},
  {id:855,name:"anthurium",latin:"Anthurium andraeanum"},
  {id:856,name:"anthurium",latin:"Anthurium crassinervium"},
  {id:8494,name:"anthurium",latin:"Anthurium andraeanum (incl. hybrid cvs.)"},
  {id:7640,name:"arrowhead plant",latin:"Syngonium podophyllum \'Neon Robusta\'"},
  {id:6070,name:"artillery plant",latin:"Pilea microphylla"},
  {id:8691,name:"artillery plant",latin:"Pilea depressa"},
  {id:6535,name:"Asian bell tree",latin:"Radermachera sinica"},
  {id:1024,name:"asparagus fern",latin:"Asparagus densiflorus \'Myersii\'"},
  {id:1025,name:"asparagus fern",latin:"Asparagus densiflorus \'Sprengeri\'"},
  {id:1031,name:"asparagus fern",latin:"Asparagus setaceus"},
  {id:5808,name:"baby rubber plant",latin:"Peperomia obtusifolia"},
  {id:7410,name:"baby\'s tears",latin:"Soleirolia soleirolii"},
  {id:8766,name:"bacopa",latin:"Sutera cordata"},
  {id:8704,name:"Balfour aralia",latin:"Polyscias balfouriana"},
  {id:1822,name:"bamboo palm",latin:"Chamaedorea seifrizii"},
  {id:2568,name:"bamboo palm",latin:"Dypsis lutescens"},
  {id:5498,name:"basil",latin:"Ocimum citriodorum \'Pesto Perpetuo\'"},
  {id:7681,name:"batflower",latin:"Tacca leontopetaloides"},
  {id:1194,name:"begonia",latin:"Begonia \'Art Hodes\'"},
  {id:1195,name:"begonia",latin:"Begonia benariensis BIG SERIES"},
  {id:1196,name:"begonia",latin:"Begonia \'Bepared\' DRAGON WING RED"},
  {id:1197,name:"begonia",latin:"Begonia boliviensis BOSSA NOVA RED"},
  {id:1198,name:"begonia",latin:"Begonia \'Canary Wing\'"},
  {id:1199,name:"begonia",latin:"Begonia \'Casper\'"},
  {id:1200,name:"begonia",latin:"Begonia \'Curly Fireflush\'"},
  {id:1201,name:"begonia",latin:"Begonia \'Dangling Pearls\'"},
  {id:1202,name:"begonia",latin:"Begonia \'Emerald Glow\'"},
  {id:1208,name:"begonia",latin:"Begonia \'Green Gold\'"},
  {id:1209,name:"begonia",latin:"Begonia \'Gryphon\'"},
  {id:1210,name:"begonia",latin:"Begonia \'Lime Royale\'"},
  {id:1211,name:"begonia",latin:"Begonia \'Martha Stewart\'"},
  {id:1213,name:"begonia",latin:"Begonia \'Penny Lahn\'"},
  {id:1216,name:"begonia",latin:"Begonia \'River Nile\'"},
  {id:1217,name:"begonia",latin:"Begonia (Semperflorens Cultorum Group)"},
  {id:1218,name:"begonia",latin:"Begonia semperflorens \'Senator Deep Rose\'"},
  {id:1221,name:"begonia",latin:"Begonia \'Solar Flare\'"},
  {id:1225,name:"begonia",latin:"Begonia tuberosa \'Fortune Peach Shades\'"},
  {id:1038,name:"bird\'s nest fern",latin:"Asplenium nidus \'Antiquum\'"},
  {id:1971,name:"bleeding heart",latin:"Clerodendrum thomsoniae"},
  {id:7164,name:"blue sansevieria",latin:"Sansevieria ehrenberghii \'Samurai Dwarf\'"},
  {id:5443,name:"blushing bromeliad",latin:"Neoregelia carolinae f. tricolor"},
  {id:7918,name:"boat lily",latin:"Tradescantia spathacea"},
  {id:5465,name:"Boston fern",latin:"Nephrolepis exaltata"},
  {id:5466,name:"Boston fern",latin:"Nephrolepis exaltata \'Bostoniensis\'"},
  {id:5467,name:"Boston fern",latin:"Nephrolepis exaltata \'Tiger Fern\'"},
  {id:7163,name:"bowstring hemp",latin:"Sansevieria cylindrica"},
  {id:7170,name:"bowstring hemp",latin:"Sansevieria suffruticosa"},
  {id:1416,name:"boxwood",latin:"Buxus microphylla \'Peergold\' GOLDEN DREAM"},
  {id:8791,name:"bromeliad",latin:"Vriesea spp."},
  {id:4280,name:"busy lizzy",latin:"Impatiens walleriana"},
  {id:5740,name:"button fern",latin:"Pellaea rotundifolia"},
  {id:8798,name:"calamondin orange",latin:"x Citrofortunella microcarpa"},
  {id:8509,name:"calathea",latin:"Calathea roseopicta"},
  {id:7569,name:"Cape primrose",latin:"Streptocarpus (group)"},
  {id:8765,name:"cape primrose",latin:"Streptocarpus x hybridus"},
  {id:8385,name:"cardboard palm",latin:"Zamia furfuracea"},
  {id:1036,name:"cast-iron plant",latin:"Aspidistra elatior"},
  {id:5444,name:"catmint",latin:"Nepeta \'Blue Dragon\'"},
  {id:5446,name:"catmint",latin:"Nepeta \'Cat\'s Pajamas\'"},
  {id:5445,name:"catnip",latin:"Nepeta cataria"},
  {id:5269,name:"centipede plant",latin:"Muehlenbeckia platyclada"},
  {id:1821,name:"chamaedorea",latin:"Chamaedorea microspadix"},
  {id:626,name:"Chinese evegreen",latin:"Aglaonema \'Cutlass\'"},
  {id:627,name:"Chinese evergreen",latin:"Aglaonema \'Red Gold\'"},
  {id:628,name:"Chinese evergreen",latin:"Aglaonema \'Silver Queen\'"},
  {id:8485,name:"Chinese evergreen",latin:"Aglaonema cvs."},
  {id:8480,name:"Chinese lantern ",latin:"Abutilon x hybridum"},
  {id:7265,name:"Christmas cactus",latin:"Schlumbergera buckleyi"},
  {id:7266,name:"Christmas cactus",latin:"Schlumbergera truncata"},
  {id:2885,name:"christplant",latin:"Euphorbia milii"},
  {id:1855,name:"chrysanthemum",latin:"Chrysanthemum \'Fireworks Igloo\'"},
  {id:1864,name:"chrysanthemum",latin:"Chrysanthemum \'Radiant Igloo\'"},
  {id:1868,name:"chrysanthemum",latin:"Chrysanthemum \'Yobra\' BRAVO"},
  {id:1870,name:"chrysanthemum",latin:"Chrysanthemum \'Yogin\' GINGER"},
  {id:1871,name:"chrysanthemum",latin:"Chrysanthemum \'Yogrena\' GRENADINE"},
  {id:1873,name:"chrysanthemum",latin:"Chrysanthemum \'Yoraquel\' RAQUEL"},
  {id:2965,name:"climbing fig",latin:"Ficus pumila"},
  {id:6199,name:"coleus",latin:"Plectranthus \'Balcenna\' HENNA"},
  {id:6200,name:"coleus",latin:"Plectranthus COLORBLAZE LIME TIME"},
  {id:6201,name:"coleus",latin:"Plectranthus COLORBLAZE ROYALE CHERRY BRANDY"},
  {id:6204,name:"coleus",latin:"Plectranthus PREMIUM SUN LIME DELIGHT"},
  {id:6205,name:"coleus",latin:"Plectranthus scutellarioides"},
  {id:6207,name:"coleus",latin:"Plectranthus \'Redhead\'"},
  {id:8699,name:"coleus",latin:"Plectranthus scutellarioides hybrids & cvs. ( syn. Solenostemon )"},
  {id:2030,name:"columnea",latin:"Columnea microcalyx"},
  {id:3986,name:"common hyacinth",latin:"Hyacinthus orientalis"},
  {id:3988,name:"common hyacinth",latin:"Hyacinthus orientalis ETOUFFEE"},
  {id:4727,name:"Cooper’s African hyacinth",latin:"Ledebouria cooperi"},
  {id:8610,name:"coral bells ",latin:"Heuchera cvs."},
  {id:8692,name:"creeping Charlie",latin:"Pilea nummulariifolia"},
  {id:8596,name:"creeping Charlie ",latin:"Glechoma hederacea"},
  {id:6405,name:"cretan brake",latin:"Pteris cretica"},
  {id:1999,name:"croton",latin:"Codiaeum variegatum"},
  {id:2000,name:"croton",latin:"Codiaeum variegatum var. pictum"},
  {id:8565,name:"crown of thorns",latin:"Euphorbia milii (incl. hybrids)"},
  {id:2244,name:"cryptanthus",latin:"Cryptanthus (group)"},
  {id:2263,name:"cuphea",latin:"Cuphea VERMILLIONAIRE"},
  {id:2275,name:"cyclamen",latin:"Cyclamen persicum"},
  {id:8543,name:"cyclamen",latin:"Cyclamen persicum (incl. hybrids)"},
  {id:2277,name:"cymbalaria",latin:"Cymbalaria aequitriloba"},
  {id:546,name:"delta maidenhair fern",latin:"Adiantum raddianum"},
  {id:540,name:"desert rose",latin:"Adenium obesum"},
  {id:2533,name:"dracaena",latin:"Dracaena sanderiana"},
  {id:2531,name:"dragontree",latin:"Dracaena marginata"},
  {id:2468,name:"dumb cane",latin:"Dieffenbachia seguine"},
  {id:6208,name:"dwarf fern-leaf bamboo",latin:"Pleioblastus pygmaeus"},
  {id:8538,name:"earth star",latin:"Cryptanthus bivittatus"},
  {id:8601,name:"Easter cactus",latin:"Hatiora x graeseri"},
  {id:7405,name:"eggplant",latin:"Solanum melongena"},
  {id:710,name:"elephant\'s ear",latin:"Alocasia amazonica"},
  {id:712,name:"elephant\'s ear",latin:"Alocasia \'Frydek\'"},
  {id:713,name:"elephant\'s ear",latin:"Alocasia (group)"},
  {id:714,name:"elephant\'s ear",latin:"Alocasia LOW RIDER"},
  {id:716,name:"elephant\'s ear",latin:"Alocasia \'Metalhead\'"},
  {id:717,name:"elephant\'s ear",latin:"Alocasia \'Portora\'"},
  {id:718,name:"elephant\'s ear",latin:"Alocasia \'Sarian\'"},
  {id:6178,name:"elkhorn fern",latin:"Platycerium bifurcatum"},
  {id:5807,name:"emerald ripple pepper",latin:"Peperomia caperata"},
  {id:3349,name:"English ivy",latin:"Hedera helix"},
  {id:3350,name:"English ivy",latin:"Hedera helix \'Arborescens\'"},
  {id:3351,name:"English ivy",latin:"Hedera helix \'Glacier\'"},
  {id:3352,name:"English ivy",latin:"Hedera helix \'Midas Touch\'"},
  {id:3353,name:"English ivy",latin:"Hedera helix \'Tango\'"},
  {id:3354,name:"English ivy",latin:"Hedera helix var. baltica"},
  {id:6210,name:"false aralia",latin:"Plerandra elegantissima"},
  {id:8743,name:"false aralia",latin:"Schefflera elegantissima"},
  {id:8677,name:"false shamrock",latin:"Oxalis triangularis"},
  {id:6252,name:"fern-leaf aralia",latin:"Polyscias filicifolia"},
  {id:2963,name:"fiddle-leaf fig",latin:"Ficus lyrata"},
  {id:2956,name:"fig",latin:"Ficus carica \'Brown Turkey\'"},
  {id:2957,name:"fig",latin:"Ficus carica \'Celeste\'"},
  {id:2958,name:"fig",latin:"Ficus carica \'Chicago Hardy\'"},
  {id:2959,name:"fig",latin:"Ficus carica \'MAJOAM\' LITTLE MISS FIGGY"},
  {id:2242,name:"firecracker flower",latin:"Crossandra infundibuliformis"},
  {id:2775,name:"flame violet",latin:"Episcia cupreata"},
  {id:5810,name:"florist\'s cineraria",latin:"Pericallis hybrida"},
  {id:425,name:"flowering-maple",latin:"Abutilon hybridum"},
  {id:426,name:"flowering-maple",latin:"Abutilon hybridum \'Bella Red\'"},
  {id:427,name:"flowering-maple",latin:"Abutilon \'Moonchimes\'"},
  {id:428,name:"flowering-maple",latin:"Abutilon pictum \'Gold Dust\'"},
  {id:7858,name:"foam flower",latin:"Tiarella \'Filigree Lace\'"},
  {id:7864,name:"foam flower",latin:"Tiarella \'Ninja\'"},
  {id:7866,name:"foam flower",latin:"Tiarella \'Pink Brushes\'"},
  {id:7873,name:"foam flower",latin:"Tiarella \'Tntia041\' STARGAZER MERCURY"},
  {id:2528,name:"fragrant dracaena",latin:"Dracaena fragrans"},
  {id:5564,name:"fragrant olive",latin:"Osmanthus fragrans"},
  {id:7189,name:"fragrant sweet box",latin:"Sarcococca ruscifolia"},
  {id:6069,name:"friendship plant",latin:"Pilea involucrata"},
  {id:3087,name:"gardenia",latin:"Gardenia jasminoides"},
  {id:3089,name:"gardenia",latin:"Gardenia jasminoides \'Crown Jewel\'"},
  {id:3090,name:"gardenia",latin:"Gardenia jasminoides \'Grif\'s Select\'"},
  {id:8588,name:"geranium",latin:"Geranium spp. and/ or cvs."},
  {id:715,name:"giant elephant\'s ear",latin:"Alocasia macrorrhizos"},
  {id:7384,name:"gloxinia",latin:"Sinningia speciosa"},
  {id:3236,name:"goeppertia",latin:"Goeppertia roseopicta"},
  {id:8550,name:"gold-dust dracaena",latin:"Dracaena surculosa"},
  {id:2773,name:"golden pothos",latin:"Epipremnum aureum"},
  {id:8836,name:"Green Mountain Maidenhair Fern",latin:"Adiantum viridimontanum"},
  {id:5588,name:"Guiana chestnut",latin:"Pachira aquatica"},
  {id:5868,name:"horsehead philodendron",latin:"Philodendron bipinnatifidum"},
  {id:502,name:"hot water plant",latin:"Achimenes (group)"},
  {id:8487,name:"hybrid ornamental onion",latin:"Allium (incl. hybrids)"},
  {id:8685,name:"hybrid philodendron",latin:"Philodendron x hybrida"},
  {id:1203,name:"hybrid tuberous begonia",latin:"Begonia FUNKY PINK"},
  {id:1223,name:"hybrid tuberous begonia",latin:"Begonia tuberhybrida \'Jurassic Pink Splash\'"},
  {id:1224,name:"hybrid tuberous begonia",latin:"Begonia tuberhybrida \'Jurassic Silver Swirl\'"},
  {id:1226,name:"hybrid tuberous begonia",latin:"Begonia (Tuberosa Group)"},
  {id:7923,name:"inch plant",latin:"Tradescantia zebrina"},
  {id:2962,name:"India rubber plant",latin:"Ficus elastica \'Burgundy\'"},
  {id:2961,name:"Indian rubberplant",latin:"Ficus elastica"},
  {id:4349,name:"iris",latin:"Iris spp."},
  {id:1212,name:"iron cross begonia",latin:"Begonia masoniana"},
  {id:5738,name:"ivyleaf geranium",latin:"Pelargonium peltatum"},
  {id:434,name:"Jacob\'s coat",latin:"Acalypha wilkesiana"},
  {id:2193,name:"jade plant",latin:"Crassula ovata"},
  {id:2294,name:"Japanese holly fern",latin:"Cyrtomium falcatum"},
  {id:2295,name:"Japanese holly fern",latin:"Cyrtomium fortunei"},
  {id:1130,name:"Japanese painted fern",latin:"Athyrium niponicum var. pictum"},
  {id:1133,name:"Japanese painted fern",latin:"Athyrium niponicum var. pictum \'Metallicum\'"},
  {id:8625,name:"jasmine",latin:"Jasminum polyanthum"},
  {id:5007,name:"jewel orchid",latin:"Ludisia (group)"},
  {id:1272,name:"jewel plant",latin:"Bertolonia maculata"},
  {id:747,name:"Joseph\'s coat",latin:"Alternanthera ficoidea"},
  {id:748,name:"Joseph\'s coat",latin:"Alternanthera ficoidea (yellow form)"},
  {id:4558,name:"kalanchoe",latin:"Kalanchoe blossfeldiana"},
  {id:4559,name:"kalanchoe",latin:"Kalanchoe thyrsiflora \'Flapjacks\'"},
  {id:6554,name:"lady palm",latin:"Rhapis excelsa"},
  {id:4722,name:"lavender",latin:"Lavandula \'Silver Frost\'"},
  {id:552,name:"lipstick plant",latin:"Aeschynanthus radicans"},
  {id:4947,name:"lobelia",latin:"Lobelia erinus"},
  {id:4956,name:"lobelia",latin:"Lobelia \'Sparkle DeVine\'"},
  {id:543,name:"maidenhair fern",latin:"Adiantum capillus-veneris"},
  {id:8722,name:"majesty palm",latin:"Ravenea rivularis"},
  {id:5203,name:"marvel of Peru",latin:"Mirabilis jalapa"},
  {id:7167,name:"Mason\'s Congo sansevieria",latin:"Sansevieria masoniana"},
  {id:1891,name:"meyer lemon",latin:"Citrus meyeri"},
  {id:6253,name:"Ming aralia",latin:"Polyscias fruticosa"},
  {id:6809,name:"miniature rose",latin:"Rosa \'Benblack\' BLACK JADE"},
  {id:6913,name:"miniature rose",latin:"Rosa \'Savasach\' SACHET"},
  {id:6920,name:"miniature rose",latin:"Rosa \'Scrivluv\' BABY LOVE"},
  {id:3972,name:"miniature wax plant",latin:"Hoya lanceolata subsp. bella"},
  {id:7919,name:"Moses-in-a-basket",latin:"Tradescantia spathacea \'Vittata\'"},
  {id:5837,name:"moth orchid",latin:"Phalaenopsis (group)"},
  {id:7165,name:"mother-in-law\'s tongue",latin:"Sansevieria \'Fernwood Mikado\'"},
  {id:7166,name:"mother-in-law\'s tongue",latin:"Sansevieria kirkii \'Silver Blue\'"},
  {id:7169,name:"mother-in-law\'s tongue",latin:"Sansevieria \'Starfish\'"},
  {id:7172,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Bantel\'s Sensation\'"},
  {id:7173,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Black Coral\'"},
  {id:7174,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Black Robusta\'"},
  {id:7175,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Black Star\'"},
  {id:7176,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Dwarf Laurentii\'"},
  {id:7177,name:"mother-in-law\'s tongue",latin:"Sansevieria trifasciata \'Gold Flame\'"},
  {id:1993,name:"Natal lily",latin:"Clivia miniata"},
  {id:3355,name:"Nepal ivy",latin:"Hedera nepalensis var. sinensis"},
  {id:5449,name:"nepeta",latin:"Nepeta faassenii \'Kit Cat\'"},
  {id:5462,name:"nepeta",latin:"Nepeta subsessilis \'Candy Cat\'"},
  {id:2976,name:"Nerve Plant",latin:"Fittonia albivenis (Argyroneura Group)"},
  {id:7244,name:"octopus tree",latin:"Schefflera actinophylla"},
  {id:667,name:"onion",latin:"Allium cepa"},
  {id:1468,name:"orchid",latin:"Calanthe \'Kozu Spice\'"},
  {id:1716,name:"orchid",latin:"Cattleya (group)"},
  {id:2279,name:"orchid",latin:"Cymbidium (group)"},
  {id:2354,name:"orchid",latin:"Dendrobium (group)"},
  {id:5520,name:"orchid",latin:"Oncidium (group)"},
  {id:5836,name:"orchid",latin:"Phaius (group)"},
  {id:5950,name:"orchid",latin:"Phragmipedium (group)"},
  {id:8422,name:"orchid",latin:"Zygopetalum (group)"},
  {id:4901,name:"orienpet lily",latin:"Lilium \'Touching\'"},
  {id:1597,name:"ornamental pepper",latin:"Capsicum annuum \'Black Pearl\'"},
  {id:1598,name:"ornamental pepper",latin:"Capsicum annuum \'Chinese Five Color\'"},
  {id:1601,name:"ornamental pepper",latin:"Capsicum annuum \'Onyx Red\'"},
  {id:1603,name:"ornamental pepper",latin:"Capsicum annuum \'Purple Flash\'"},
  {id:8512,name:"ornamental pepper",latin:"Capsicum annuum cv."},
  {id:1820,name:"parlor palm",latin:"Chamaedorea elegans"},
  {id:5726,name:"passion flower",latin:"Passiflora \'Incense\'"},
  {id:8679,name:"passion flower",latin:"Passiflora (incl. hybrids)"},
  {id:7463,name:"peace lily",latin:"Spathiphyllum (group)"},
  {id:8763,name:"peace lily",latin:"Spathiphyllum cvs."},
  {id:1470,name:"peacock plant",latin:"Calathea makoyana"},
  {id:8681,name:"pelargonium",latin:"Pelargonium x domesticum"},
  {id:4122,name:"pennywort",latin:"Hydrocotyle vulgaris"},
  {id:3347,name:"Persian ivy",latin:"Hedera colchica"},
  {id:2274,name:"Persian violet",latin:"Cyclamen hederifolium"},
  {id:2915,name:"Persian violet",latin:"Exacum affine"},
  {id:625,name:"Philippine evergreen",latin:"Aglaonema commutatum"},
  {id:5870,name:"philodendron",latin:"Philodendron \'Pink Princess\'"},
  {id:5871,name:"philodendron",latin:"Philodendron \'Winterbourn\' XANADU"},
  {id:8778,name:"piggyback plant",latin:"Tolmiea menziesii"},
  {id:6071,name:"pilea",latin:"Pilea mollis \'Moon Valley\'"},
  {id:2891,name:"poinsettia",latin:"Euphorbia pulcherrima"},
  {id:4181,name:"polka dot plant",latin:"Hypoestes phyllostachya"},
  {id:4182,name:"polka dot plant",latin:"Hypoestes phyllostachya \'Confetti Compact White\'"},
  {id:4183,name:"polka dot plant",latin:"Hypoestes phyllostachya SPLASH SELECT PINK"},
  {id:1192,name:"ponytail palm",latin:"Beaucarnea recurvata"},
  {id:7409,name:"potato",latin:"Solanum tuberosum"},
  {id:2774,name:"pothos",latin:"Epipremnum aureum \'Neon\'"},
  {id:5159,name:"prayer plant",latin:"Maranta leuconeura var. erythroneura"},
  {id:8653,name:"prayer plant",latin:"Maranta leuconeura var. kerchoviana"},
  {id:6311,name:"primula",latin:"Primula vialii"},
  {id:6317,name:"primula",latin:"Primula \'Wanda Kay\'"},
  {id:6318,name:"primula",latin:"Primula \'Wanda Renae\'s Pearl\'"},
  {id:8709,name:"primula",latin:"Primula vulgaris (incl. hybrids)"},
  {id:2322,name:"rabbit\'s foot fern",latin:"Davallia fejeensis"},
  {id:2323,name:"rabbit\'s foot fern",latin:"Davallia fejeensis \'Dwarf Ripple\'"},
  {id:1469,name:"rattlesnake plant",latin:"Calathea lancifolia"},
  {id:3637,name:"red ivy",latin:"Hemigraphis alternata"},
  {id:8652,name:"red-veined prayer plant",latin:"Maranta leuconeura \'Erythroneura\'"},
  {id:5736,name:"regal geranium",latin:"Pelargonium domesticum"},
  {id:1214,name:"rex begonia",latin:"Begonia rex-cultorum"},
  {id:1215,name:"rex begonia",latin:"Begonia rex-cultorum \'Super Curl\'"},
  {id:8549,name:"ribbon plant",latin:"Dracaena braunii"},
  {id:2272,name:"Sago palm",latin:"Cycas revoluta"},
  {id:7276,name:"satin pothos",latin:"Scindapsus pictus \'Argyraeus\'"},
  {id:3256,name:"scarlet star",latin:"Guzmania lingulata"},
  {id:5739,name:"scented-leaved geranium",latin:"Pelargonium (scented-leaved group)"},
  {id:5180,name:"showy medinilla",latin:"Medinilla magnifica"},
  {id:4554,name:"shrimp plant",latin:"Justicia brandegeeana \'Yellow Queen\'"},
  {id:8682,name:"silver-leaf peperomia",latin:"Peperomia griseoargentea"},
  {id:7911,name:"small-leaf spiderwort",latin:"Tradescantia fluminensis"},
  {id:7168,name:"snake plant",latin:"Sansevieria patens"},
  {id:7352,name:"snowrose",latin:"Serissa japonica"},
  {id:7353,name:"snowrose",latin:"Serissa japonica \'Kowloon\'"},
  {id:7354,name:"snowrose",latin:"Serissa japonica \'Variegata\'"},
  {id:2532,name:"song of India",latin:"Dracaena reflexa \'Variegata\'"},
  {id:8132,name:"speedwell",latin:"Veronica \'Mann\'s Variety\'"},
  {id:7917,name:"spider lily",latin:"Tradescantia pallida \'Purpurea\'"},
  {id:7921,name:"spider lily",latin:"Tradescantia tharpii"},
  {id:1846,name:"spider plant",latin:"Chlorophytum \'Bonnie\'"},
  {id:1847,name:"spider plant",latin:"Chlorophytum comosum \'Vittatum\'"},
  {id:1848,name:"spider plant",latin:"Chlorophytum \'Fire Flash\'"},
  {id:7901,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Blushing Bride\'"},
  {id:7902,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Concord Grape\'"},
  {id:7903,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Little Doll\'"},
  {id:7904,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Mariella\'"},
  {id:7905,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Purple Profusion\'"},
  {id:7906,name:"spiderwort",latin:"Tradescantia \'Red Cloud\'"},
  {id:7907,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Snowcap\'"},
  {id:7908,name:"spiderwort",latin:"Tradescantia (Andersoniana Group) \'Sweet Kate\'"},
  {id:7910,name:"spiderwort",latin:"Tradescantia ernestiana"},
  {id:7912,name:"spiderwort",latin:"Tradescantia fluminensis \'Albovittata\'"},
  {id:7913,name:"spiderwort",latin:"Tradescantia \'Hawaiian Punch\'"},
  {id:7914,name:"spiderwort",latin:"Tradescantia longipes"},
  {id:7915,name:"spiderwort",latin:"Tradescantia \'Lucky Charm\'"},
  {id:8377,name:"Spineless yucca",latin:"Yucca elephantipes"},
  {id:8683,name:"spoon leaf peperomia",latin:"Peperomia magnoliifolia"},
  {id:1147,name:"spotted laurel",latin:"Aucuba japonica \'Mr. Goldstrike\'"},
  {id:1149,name:"spotted laurel",latin:"Aucuba japonica \'Suruga Benten\'"},
  {id:1150,name:"spotted laurel",latin:"Aucuba japonica \'Variegata\'"},
  {id:1023,name:"Sprenger\'s asparagus fern",latin:"Asparagus densiflorus"},
  {id:1845,name:"St. Bernard\'s lily",latin:"Chlorophytum amaniense"},
  {id:551,name:"stalked aeonium",latin:"Aeonium undulatum"},
  {id:8520,name:"string of hearts",latin:"Ceropegia linearis ssp. woodii"},
  {id:7345,name:"string of pearls",latin:"Senecio rowleyanus"},
  {id:8755,name:"string-of-pearls ",latin:"Senecio rowleyanus (syn. Curio rowleyanus)"},
  {id:2529,name:"striped dracaena",latin:"Dracaena fragrans (Deremensis Group) \'Lemon Lime\'"},
  {id:2530,name:"striped dracaena",latin:"Dracaena fragrans (Deremensis Group) \'Limelight\'"},
  {id:7571,name:"stromanthe",latin:"Stromanthe sanguinea"},
  {id:7572,name:"stromanthe",latin:"Stromanthe sanguinea \'Tristar\'"},
  {id:6197,name:"Swedish ivy",latin:"Plectranthus australis"},
  {id:6202,name:"Swedish ivy",latin:"Plectranthus forsteri \'Marginatus\'"},
  {id:6203,name:"Swedish ivy",latin:"Plectranthus \'Mona Lavender\'"},
  {id:6206,name:"Swedish ivy",latin:"Plectranthus strigosus"},
  {id:8700,name:"Swedish ivy",latin:"Plectranthus verticillatus"},
  {id:5497,name:"sweet basil",latin:"Ocimum basilicum"},
  {id:7186,name:"sweet box",latin:"Sarcococca hookeriana"},
  {id:7187,name:"sweet box",latin:"Sarcococca hookeriana var. humilis"},
  {id:7188,name:"sweet box",latin:"Sarcococca hookeriana var. humilis \'Sarsid2\' FRAGRANT MOUNTAIN"},
  {id:4304,name:"sweet potato vine",latin:"Ipomoea batatas SWEET CAROLINE BEWITCHED GREEN WITH ENVY"},
  {id:8622,name:"sweet potato vine",latin:"Ipomoea batatas cvs."},
  {id:5257,name:"Swiss cheese plant",latin:"Monstera deliciosa"},
  {id:8717,name:"table fern",latin:"Pteris ensiformis"},
  {id:1001,name:"trailing snapdragon",latin:"Asarina procumbens"},
  {id:5741,name:"trailing watermelon begonia",latin:"Pellionia repens"},
  {id:7743,name:"tropical almond",latin:"Terminalia catappa"},
  {id:8004,name:"tulip",latin:"Tulipa (group)"},
  {id:2287,name:"umbrella plant",latin:"Cyperus alternifolius \'Variegatus\'"},
  {id:2288,name:"umbrella plant",latin:"Cyperus involucratus"},
  {id:2289,name:"umbrella plant",latin:"Cyperus involucratus \'Baby Tut\'"},
  {id:2290,name:"umbrella plant",latin:"Cyperus involucratus \'Gracilis\'"},
  {id:7245,name:"umbrella plant",latin:"Schefflera arboricola"},
  {id:549,name:"urn plant",latin:"Aechmea fasciata"},
  {id:8603,name:"variegated Persian ivy",latin:"Hedera colchica \'Sulfur Heart\'"},
  {id:5258,name:"variegated Swiss cheese plant",latin:"Monstera deliciosa \'Variegata\'"},
  {id:4557,name:"velvet leaf kalanchoe",latin:"Kalanchoe beharensis"},
  {id:3259,name:"velvet plant",latin:"Gynura aurantiaca"},
  {id:2498,name:"Venus fly trap",latin:"Dionaea muscipula"},
  {id:2499,name:"Venus fly trap",latin:"Dionaea muscipula \'Akai Ryu\'"},
  {id:2500,name:"Venus fly trap",latin:"Dionaea muscipula \'Cup-shaped\'"},
  {id:2501,name:"Venus fly trap",latin:"Dionaea muscipula \'King Henry\'"},
  {id:5706,name:"Venus\' slipper",latin:"Paphiopedilum (group)"},
  {id:5869,name:"vilevine",latin:"Philodendron hederaceum"},
  {id:7171,name:"viper\'s bowstring hemp",latin:"Sansevieria trifasciata"},
  {id:8314,name:"vriesea",latin:"Vriesea splendens"},
  {id:5589,name:"water chestnut",latin:"Pachira aquatica \'Lemon Blush\'"},
  {id:5806,name:"watermelon peperomia",latin:"Peperomia argyreia"},
  {id:1219,name:"wax begonia",latin:"Begonia semperflorens-cultorum \'Harmony Scarlet\'"},
  {id:3971,name:"wax plant",latin:"Hoya carnosa"},
  {id:2954,name:"weeping fig",latin:"Ficus benjamina"},
  {id:2955,name:"weeping fig",latin:"Ficus benjamina \'Variegata\'"},
  {id:7890,name:"wishbone flower",latin:"Torenia fournieri"},
  {id:8794,name:"yucca",latin:"Yucca filamentosa (incl. hybrid cvs.)"},
  {id:861,name:"zebra plant",latin:"Aphelandra squarrosa"},
  {id:1471,name:"zebra plant",latin:"Calathea zebrina"},
  {id:7920,name:"zigzag spiderwort",latin:"Tradescantia subaspera"},
  {id:5737,name:"zonal geranium",latin:"Pelargonium hortorum"},
  {id:8680,name:"zonal geranium",latin:"Pelargonium x hortorum"},
  {id:8386,name:"ZZ plant",latin:"Zamioculcas zamiifolia"},
  {id:8387,name:"ZZ plant",latin:"Zamioculcas zamiifolia \'Raven\'"},
];

Object.assign(window, {
  PERENUAL, INDOOR_PLANTS, speciesCare, searchSpecies, searchLocalPlants, getSpeciesDetails, identifySpecies,
  setApiKey, hasApiKey, SEED_PLANTS,
});
